version: '3.7'

services:
  nodejs:
    image: node:12.18-alpine
    container_name: nodejs
    restart: unless-stopped
    env_file: .env
    working_dir: "/home/node/app"
    links: 
      - db
    depends_on: 
      - db
    environment:
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_HOSTNAME=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_DB=${MONGO_DB}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    volumes:
      - .:/home/node/app
    networks:
      - example
    command: node_modules/.bin/nodemon app.js
  db:
    image: mongo:4.1.8-xenial
    container_name: db
    restart: unless-stopped
    env_file: .env
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:     
      - dbdata:/data/db
    networks:
      - example
networks:
  example:
    driver: bridge
volumes:
  dbdata:
  node_modules:  
